@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package io.github.florianraediker.customsplashes.client.util;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;