@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package io.github.florianraediker.customsplashes.client.util.splash;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;